### ISSUE TITLE
Макет контрольной

### ISSUE THREAD

**Issue by rosshkaa** [moevm/mse_generator_of_test_works_for_Stepik#2]
Необходимо перечислить все поля данных которые включает в себя контрольная на степике

**Comment by AleksandrRybin** [comment]
Перенес в milestone 0.3, т.к. вид ещё кр не согласован с руководителем проекта

**Comment by AleksandrRybin** [comment]
Перенос в issue #12

**Comment by rosshkaa** [comment]
Для начала можно выгружать только тесты. Впоследствии необходимо модифицировать до выгрузки всех актуальных типов задач.
