### ISSUE TITLE
Страничка настройки генерации

### ISSUE THREAD

**Issue by AleksandrRybin** [moevm/mse_generator_of_test_works_for_Stepik#25]
После выбора курса для генерации пользователь попадает на эту страничку.
Она содержит следующие поля:
- Имя курса для генерации как заголовок формы
- Поле для ввода названия контрольной
- Слайдер для ввода количества вариантов контрольной
 - Слайдер для ввода количества заданий в одном варианте
 - Выбор модулей(*уроков, степов*) для генерации *(пока можно только модулей)*
- Кнопка генерации, которая перенапрвляет на *url_for('generate')*

**Comment by destrosw** [comment]
#28
