### ISSUE TITLE
Исследование: API для загрузки контрольной

### ISSUE THREAD

**Issue by rosshkaa** [moevm/mse_generator_of_test_works_for_Stepik#3]
Необходимо исследовать возможности Stepic API (https://github.com/StepicOrg/Stepik-API ) и перечислить методы, необходимые для загрузки контрольной и получения данных о существующих контрольных

**Comment by chelentos** [comment]
Как я понял, мы с помощью того, что реализовано [тут](https://github.com/StepicOrg/Stepik-API/blob/master/examples/export_course.py) загружаем курс, создаются файлы со степами, а потом с помощью [этого](https://github.com/StepicOrg/Stepik-API/blob/master/examples/create_content.py) делаем в курсе урок "Контрольная", в котором степами будут задания.

**Comment by chelentos** [comment]
На данный момент сделан файл для загрузки курса через указание ключей и айди курса в командной строке для последующей работы с этими данными, реализация выгрузки на степик заморожена до получения деталей по поводу того, как именно должна быть реализована контрольная(урок/модуль).

**Comment by AleksandrRybin** [comment]
Перенос в issue #12
