### ISSUE TITLE
Презентация к окончанию этапа 0.3

### ISSUE THREAD

**Issue by AleksandrRybin** [moevm/mse_generator_of_test_works_for_Stepik#50]

**Comment by yourBunnyVVrote** [comment]
![image](https://user-images.githubusercontent.com/21955323/48862644-08228900-edd8-11e8-88d9-28fc9e3f0129.png)

**Comment by yourBunnyVVrote** [comment]
![image](https://user-images.githubusercontent.com/21955323/48862662-1375b480-edd8-11e8-887a-7f76c84a7663.png)

**Comment by yourBunnyVVrote** [comment]
![image](https://user-images.githubusercontent.com/21955323/48862675-1bcdef80-edd8-11e8-9e61-a11ea72ec0c9.png)

**Comment by yourBunnyVVrote** [comment]
![image](https://user-images.githubusercontent.com/21955323/48862685-22f4fd80-edd8-11e8-9269-ee0c68113783.png)

**Comment by yourBunnyVVrote** [comment]
![image](https://user-images.githubusercontent.com/21955323/48862706-2be5cf00-edd8-11e8-91e6-dc654013d27d.png)

**Comment by yourBunnyVVrote** [comment]
![image](https://user-images.githubusercontent.com/21955323/48862714-33a57380-edd8-11e8-8fc9-8d4f3cc2d13c.png)
